spring:
  datasource:
    url: jdbc:mariadb://localhost:43306/ohguohgu
    driver-class-name: org.mariadb.jdbc.Driver
    username: ohguohgu_user
    password: a1234

  thymeleaf:
    cache: false

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: bomilee.dev@gmail.com
    password: utujtmguykygasds
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher