spring:
  datasource:
    url: jdbc:mariadb://ohguohgurds.ckmkncl43d8r.ap-northeast-2.rds.amazonaws.com
    driver-class-name: org.mariadb.jdbc.Driver
    username: ohguohguadmin
    password: bomi2245

  thymeleaf:
    cache: false

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: bomilee.dev@gmail.com
    password: utujtmguykygasds
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher